# Generated by Django 3.2.5 on 2021-07-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catbusters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
