# Generated by Django 3.2.4 on 2021-07-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
