# Generated by Django 3.2.4 on 2021-07-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_auto_20210716_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='pokedex.PokemonType'),
        ),
    ]
