# Generated by Django 3.2.4 on 2021-07-02 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20210701_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='text',
            new_name='texts',
        ),
    ]
