# Generated by Django 3.2.4 on 2021-07-02 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_rename_text_mymodel_texts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='texts',
            new_name='myfield',
        ),
    ]
