# Generated by Django 3.2.4 on 2021-07-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210706_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
