# Generated by Django 3.2.4 on 2021-07-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='visits',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
