# Generated by Django 3.2.4 on 2021-06-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_alter_shortenedurl_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
