# Generated by Django 3.2.4 on 2021-06-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yellowpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ed',
            new_name='Ad',
        ),
    ]
