# Generated by Django 3.2.4 on 2021-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_is_cool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_cool',
            field=models.BooleanField(),
        ),
    ]
