# Generated by Django 3.2.4 on 2021-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image_back',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='image_front',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(related_name='pokemon', to='lab3.PokemonType'),
        ),
    ]
