# Generated by Django 3.2.4 on 2021-09-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_user_blogpost_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='username',
            new_name='username_id',
        ),
    ]
