# Generated by Django 3.2.4 on 2021-09-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_username_blogpost_username_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='username_id',
        ),
    ]
