# Generated by Django 3.2.4 on 2021-07-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemontype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
