# Generated by Django 3.2.4 on 2021-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_front', models.CharField(max_length=150)),
                ('image_back', models.CharField(max_length=150)),
                ('types', models.ManyToManyField(to='pokedex.PokemonType')),
            ],
        ),
    ]
