# Generated by Django 3.2.4 on 2021-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
