# Generated by Django 3.2.4 on 2021-07-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_auto_20210724_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.CharField(default='temp', max_length=150),
            preserve_default=False,
        ),
    ]
