# Generated by Django 3.2.4 on 2021-07-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_auto_20210730_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='types',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='types',
            field=models.ManyToManyField(to='pokedex.PokemonType'),
        ),
    ]
