# Generated by Django 3.2.4 on 2021-06-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yellowpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
